server:
  port: 12000
spring:
  aop:
    auto: true #启动aop配置
  datasource:
    master:
      url: jdbc:oracle:thin:@//39.105.67.69:1521/PSRMPDB
      username: PORTAL_UAT
      password: PORTAL_UAT
      driver-class-name: oracle.jdbc.driver.OracleDriver

    slave:
      url: jdbc:oracle:thin:@//39.105.67.69:1521/PSRMPDB
      username: CISADM
      password: CISADM
      driver-class-name: oracle.jdbc.driver.OracleDriver
      enabled: true
#解决循环依赖问题，springboot 2.1.2之后解决了
# spring.datasource.initialize=false
